jobs:

  - name: dv-man-1
    type: manifest
    steps:
      - IN: dv-image
      - IN: repo
   
  - name: simplerunsh
    type: runSh
    steps:
      - IN: repo
      - TASK:
        - script: ls
        #- script: ./GET/infra-repo/infra-repo/provision.sh
    always:
      - script: echo "This works on_always"
