jobs:
  - name: climanifest1
    type: manifest
    steps:
      - IN: cli-image1
        pull: true
  
  - name: clikubedeploy
    type: deploy
    steps:
      - IN: climanifest1
      - IN: clikubecluster
      - TASK: managed
        
