jobs:
 
  - name: VT1_runCI
    type: runCI
    steps:
      - OUT: test_params
  
  - name: VT2_runCI
    type: runCI
    steps:
      - IN: test_params
      - IN: VT1_runCI
      
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false
      - IN: VT1_runCI
  
