jobs:
  - name: base_manifest
    type: manifest
    steps:
      - IN: nginx_prod_6

  - name: failed_manifest
    type: manifest
    steps:
      - IN: base_manifest
      
      
  - name: skipped_manifest
    type: manifest
    steps:
      - IN: nginx_prod_6      
      
  - name: cancelled_runSh
    type: runSh
    steps:
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 60
    on_success:
      - script: echo "successfully completed"      
      
  - name: inconsistent_manifest
    type: manifest
    steps:
      - IN: nginx_prod_7  
      
  - name: unbuilt_manifest
    type: manifest
    steps:
      - IN: nginx_prod_6       
      
  - name: success_manifest
    type: manifest
    steps:
      - IN: nginx_prod_6     
      
      
  - name: runSh-main
    type: runSh
    steps: 
      - IN: base_manifest  
      - TASK:
        - script: echo "true"
    on_success:
      - script: echo "successfully completed"           
