jobs:
  - name: ecs-mani
    type: manifest
    steps:
      - IN: ecs-dv-image
        
  - name: lb-ecs-deploy
    type: deploy
    steps:
      - IN: ecs-mani
      - IN: ecscluster
      - TASK: managed
        #deployMethod: replace
