jobs:
- name: dv-man-tripub
    type: manifest
    steps:
      - IN: dv-image-tripub
        pull: false

# # TEST deployment to Triton
  - name: deploy-tripubbluegreen
    type: deploy  
    steps:      
      - IN: dv-man-tripub
      - IN: triton_cluster
      - TASK: managed
