jobs:
  - name: deployService-2
    type: provision
    steps:
      - IN: sn-gke-service-lb 
      - IN: dv-image-lb
  
  - name: deployService-k
    type: provision
    steps:
      - IN: sn-kube-service-lb

