jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false

  - name: multi-manifest
    type:  deploy
    steps:
      - IN: dv-man

  - name: release-one
    type: release
    steps:
      - IN: dv-man
      - TASK: managed
        bump: major

  - name: infra-provision
    type: runSh
    steps:
      - IN: dv-man
      - IN: deep_gh_ssh
      - TASK:
        - script: cd IN/
        - script: cd deep_gh_ssh/
        - script: ls -a
        - script: ssh -tt -i "deep_gh_ssh_key.pub" ubuntu@ec2-54-89-188-192.compute-1.amazonaws.com 'touch hello1.txt'
        
        - script: echo "integration name------>-"$OLDSSHKEY_NAME
        - script: echo "public key------>-"$OLDSSHKEY_INTEGRATION_PUBLICKEY
        - script: echo "private key----->-"$OLDSSHKEY_INTEGRATION_PRIVATEKEY
        - script: echo "public key path----->-"$OLDSSHKEY_PUBLIC_KEY_PATH
        - script: echo "private key path------->-"$OLDSSHKEY_PRIVATE_KEY_PATH
        - script: 
        
