jobs:
  - name: simplerunsh
    type: runSh
    steps:
      - IN: repo
      - TASK:
        - script: ls
        - script: echo "sourcename--> " $SIMPLERUNSH_SOURCENAME
        #- script: ./GET/infra-repo/infra-repo/provision.sh
    always:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack
