jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionName: latest
        versionNumber: 0
      - IN: dv-opts
      - IN: trigger-dv-man
    on_success:
      - NOTIFY: slackNotification
    on_failure:
      - NOTIFY: slackNotification
    flags:
      - dv

  - name: dv-dep-test
    type: deploy
    on_start:
      - NOTIFY: slackNotification
    steps:
      - IN: env-test
        versionName: latest
        versionNumber: 0
        pull: false
      - TASK: managed
        deployMethod: upgrade
    on_failure:
      - NOTIFY: slackNotification

  - name: box-man
    type: manifest
    steps:
      - OUT: box-image
      - TASK: managed
    flags:
      - box
    

  - name: multi-manifest
    type:  deploy
    steps:
      - IN: box-man
      - IN: dv-man
      - IN: env-test

  - name: release-one
    type: release
    steps:
      - TASK: managed
        bump: major

  - name: infra-provision
    type: runSh
    steps:
      - IN: release-one
      - TASK:
        - script: ls
        - script: echo $FOO
    on_success:
      - NOTIFY: slackNotification
      - NOTIFY: myEmail
