jobs:
 
  - name: VT1_runCI
    type: runCI
    steps:
      - OUT: test_params
  
  - name: VT2_runCI
    type: runCI
    steps:
      - IN: test_params
      - IN: dv-man-citest
      - IN: VT1_runCI
      
  - name: dv-man-citest
    type: manifest
    steps:
      - IN: dv-image-citest
        pull: false
  
