jobs:
 
  - name: VT2_runCI
    type: runCI
    steps:
      - IN: VT1_runCI
      - TASK:
        - script: export $TRIGGER_REASON=BaseImgChanged
        - script: echo"this is--"$TRIGGER_REASON
      
  
