jobs:
   - name: sn-provision
     type: provision
     steps:
       - IN: sn-img-1
  
   - name: deployService-2
     type: provision
     steps:
       - IN: sn-kube-service-lb

   - name: deployService-2
     type: provision
     steps:
       - IN: sn-kube-service-lb
