jobs:
  - name: lb-ecs-mani
    type: manifest
    steps:
      - IN: lb-dv-image
      #- IN: ecsdopts3000
        
  - name: lb-ecs-deploy
    type: deploy
    steps:
      - IN: lb-ecs-mani
      - IN: ecscluster
      - IN: lb-ecs
        applyTo:
          - manifest: lb-ecs-mani
            image: lb-dv-image
            port: 3000
      - TASK: managed
        #deployMethod: replace
