jobs:
  
  - name: dockerPullJob
    type: runSh
    steps:
      - IN: ecrConfig
      scopes:
          - ecr
      - TASK:
        - script: docker pull 742038439709.dkr.ecr.us-west-2.amazonaws.com/sample_java:latest
        
