jobs:
  - name: dockerPullJob
    type: runSh
    steps:
      - IN: ecrConfig
        switch: off
        scopes:
          - ecr
      - TASK:
        - script: docker pull 371325283159.dkr.ecr.eu-central-1.amazonaws.com/sample-code-test:latest
   
  - name: dockerPullJobNew
    type: runSh
    steps:
      - IN: ecrConfigNew
        scopes:
          - ecr
      - TASK:
        - script: docker push 742038439709.dkr.ecr.us-west-2.amazonaws.com/sample_java:latest
